# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
# sudo su postgres -c "/usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start"
$script = <<~SCRIPT
  echo "-------------------- updating package lists"
  apt-get update
  # gotta put this before the upgrade, b/c it reboots and then all commands are lost
  echo "-------------------- installing postgres"
  apt-get -y install postgresql
  # fix permissions
  echo "-------------------- fixing listen_addresses on postgresql.conf"
  sudo sed -i "s/#listen_address.*/listen_addresses '*'/" /etc/postgresql/10/main/postgresql.conf
  echo "-------------------- fixing postgres pg_hba.conf file"
  # replace the ipv4 host line with the above line
  ([[ -n $(sudo grep "0.0.0.0" /etc/postgresql/10/main/pg_hba.conf) ]] && echo "0.0.0.0/0 already listed") || sudo cat >> /etc/postgresql/10/main/pg_hba.conf <<EOF
  # Accept all IPv4 connections - FOR DEVELOPMENT ONLY!!!
  host    all         all         0.0.0.0/0             md5
  EOF

  echo "-------------------- creating postgres vagrant role with password vagrant"
  # Create Role and login
  sudo su postgres -c "psql -c \\\"CREATE ROLE vagrant SUPERUSER LOGIN PASSWORD 'vagrant'\\\" "
  echo "-------------------- creating eventstore database"
  # Create EventStore database
  sudo su postgres -c "createdb -E UTF8 -T template0 --locale=en_US.utf8 -O vagrant EventStore"
  echo "-------------------- upgrading packages to latest"
  apt-get upgrade -y
  sudo service postgresql restart
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/bionic64"

  # speed up apt-get
  # config.cache.auto_detect = true

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 5432, host: 5433

  # Run the shell script inline provisioner
  config.vm.provision "shell", run: "always", inline: $script

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

end